### ISSUE TITLE
Improve directory search @epflbot 

### ISSUE THREAD

**Issue by mukel** [epflbot/epflbot#38]
Add direct chat link for EPFL logged users.
For non-logged users just give link to EPFL page.

**Comment by mukel** [comment]
I propose to scrap the whole EPFL directory into our ES DB (at most ~20000 entries including external members), and update/rebuild it once per semester or something like that. This will drastically improve the already awkward and unstable delay.  @aimeemontero 

I've been playing a bit with ES and the search "as-is" is not enough, matches only full words, tildes are a problem e.g. Aimée != Aimee and so on. So @zifeo, would you help with the index/search to handle such cases?

Adding the search functionality to the bot is quite easy but not worth it if the search is broken.
The improved search can be also used for searching authenticated users.

**Comment by zifeo** [comment]
For mirroring, it would be more efficient to access it via LDAP (see [here](https://github.com/zifeo/Myjob/blob/master/app/Agepinfo/LDAP.php)). I can provide for sure the indexing configuration for avoiding this kind of issue :)
