### ISSUE TITLE
Log disappeared

### ISSUE THREAD

**Issue by zifeo** [epflbot/epflbot#85]
Cannot debug tequila redirection, any idea @mukel ? The HTTP log is unreachable.

**Comment by mukel** [comment]
The bot is redirecting Tequila to https://epfl.life:80 (bad port).

To test it locally, spawn ngrok http 8080 ...
Set "tequilaRedirectPort" = 443
And set "port" to 8080 (same as ngrok)

**Comment by zifeo** [comment]
When I corrected it, there is a 500 somehow, do not we have any logging for this?

**Comment by mukel** [comment]
OMG Not a single thing is logged for authentication, I'm sending a PR ASAP.

**Comment by mukel** [comment]
I can confirm that Tequila authentication works locally; you must run the LDAP scrapper as well to populate the DB; otherwise you won't be able to login.
